{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance)(irate(node_cpu_seconds_total{instance=\"localhost:9100\",mode=\"idle\"}[5m]))) * 100"
    }
   ]
  },
  {
   "title": "RAM free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "доступная оперативная память"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"localhost:9100\",mountpoint=\"/\"}",
     "legendFormat": "доступная память"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"localhost:9100\",mountpoint=\"/\"} - node_filesystem_avail_bytes{instance=\"localhost:9100\",mountpoint=\"/\"}",
     "legendFormat": "занятая память"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"localhost:9100\",mountpoint=\"/\"}",
     "legendFormat": "всего памяти"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device=\"sda\",instance=\"localhost:9100\"}[10m])",
     "legendFormat": "кол-во операций ввода/вывода на жестком диске"
    }
   ]
  }
 ]
}